//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numbers_Windows.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Numbers_Windows.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nError working with the file system: {ex.Message}.
        /// </summary>
        internal static string CreatingDirectoryErrorPrompt {
            get {
                return ResourceManager.GetString("CreatingDirectoryErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a folder &quot;{targetDir}&quot;....
        /// </summary>
        internal static string CreatingDirectoryPrompt {
            get {
                return ResourceManager.GetString("CreatingDirectoryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder successfully created! .
        /// </summary>
        internal static string CreatingDirectorySuccessPrompt {
            get {
                return ResourceManager.GetString("CreatingDirectorySuccessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number: .
        /// </summary>
        internal static string EnterNumberAgainPrompt {
            get {
                return ResourceManager.GetString("EnterNumberAgainPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number (must be in the range 1 to {maxNumber:N0}): .
        /// </summary>
        internal static string EnterNumberPrompt {
            get {
                return ResourceManager.GetString("EnterNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file will be saved in: &quot;{targetDir}&quot;.
        /// </summary>
        internal static string FileDirectoryPrompt {
            get {
                return ResourceManager.GetString("FileDirectoryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved! File path:\n&quot;{filePath}&quot;.
        /// </summary>
        internal static string FilePathPrompt {
            get {
                return ResourceManager.GetString("FilePathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {fileSizeInBytes:N0} bytes ({fileSizeInMB:F2} MB).
        /// </summary>
        internal static string FileSizePrompt {
            get {
                return ResourceManager.GetString("FileSizePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nGeneration and output of numbers to the console. Please wait....
        /// </summary>
        internal static string GenerationAndOutputPrompt {
            get {
                return ResourceManager.GetString("GenerationAndOutputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number..
        /// </summary>
        internal static string InvalidNumberPrompt {
            get {
                return ResourceManager.GetString("InvalidNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found language &quot;{lang}&quot;. Setting to EN - English...\n.
        /// </summary>
        internal static string LanguageNeutralPrompt {
            get {
                return ResourceManager.GetString("LanguageNeutralPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN - English\nES - Español\nUK - Українська.
        /// </summary>
        internal static string LanguageOptionsPrompt {
            get {
                return ResourceManager.GetString("LanguageOptionsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your language: .
        /// </summary>
        internal static string LanguagePrompt {
            get {
                return ResourceManager.GetString("LanguagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the app to language &quot;{lang}&quot;...\n.
        /// </summary>
        internal static string LanguageSettingPrompt {
            get {
                return ResourceManager.GetString("LanguageSettingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the method you need:\n1. Increase (1 2 ... 9 10)\n2. Decrease (10 9 ... 2 1)\nEnter the method number: .
        /// </summary>
        internal static string MethodChoicePrompt {
            get {
                return ResourceManager.GetString("MethodChoicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number (must be in the range of 1 to 2). Please try again.\nEnter number: .
        /// </summary>
        internal static string MethodChoiceWrongPrompt {
            get {
                return ResourceManager.GetString("MethodChoiceWrongPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nPress [Enter] to close the app....
        /// </summary>
        internal static string PressEnterPrompt {
            get {
                return ResourceManager.GetString("PressEnterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording cancelled..
        /// </summary>
        internal static string SaveFileCancelledPrompt {
            get {
                return ResourceManager.GetString("SaveFileCancelledPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save these numbers to the &quot;{fileName}&quot; file? .
        /// </summary>
        internal static string SaveFileChoicePrompt {
            get {
                return ResourceManager.GetString("SaveFileChoicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\nY/yes = Write to file | Other key = Do not write.
        /// </summary>
        internal static string SaveFileOptionsPrompt {
            get {
                return ResourceManager.GetString("SaveFileOptionsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File entry....
        /// </summary>
        internal static string SaveFileProcessPrompt {
            get {
                return ResourceManager.GetString("SaveFileProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is not suitable (must be in the range of 1 to {maxNumber:N0}). Try again..
        /// </summary>
        internal static string WrongNumberPrompt {
            get {
                return ResourceManager.GetString("WrongNumberPrompt", resourceCulture);
            }
        }
    }
}
