//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numbers_Android.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Numbers.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error working with the file system: {ex.Message}.
        /// </summary>
        public static string CreatingDirectoryErrorPrompt {
            get {
                return ResourceManager.GetString("CreatingDirectoryErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a folder &quot;{targetDir}&quot;....
        /// </summary>
        public static string CreatingDirectoryPrompt {
            get {
                return ResourceManager.GetString("CreatingDirectoryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder successfully created! .
        /// </summary>
        public static string CreatingDirectorySuccessPrompt {
            get {
                return ResourceManager.GetString("CreatingDirectorySuccessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number: .
        /// </summary>
        public static string EnterNumberAgainPrompt {
            get {
                return ResourceManager.GetString("EnterNumberAgainPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number (must be in the range 1 to {maxNumber:N0}): .
        /// </summary>
        public static string EnterNumberPrompt {
            get {
                return ResourceManager.GetString("EnterNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try giving Numbers permission to access all files..
        /// </summary>
        public static string ErrorAccessPrompt {
            get {
                return ResourceManager.GetString("ErrorAccessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Permission to write to storage was denied..
        /// </summary>
        public static string ErrorPermissionPrompt {
            get {
                return ResourceManager.GetString("ErrorPermissionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file will be saved in &quot;{targetDir}&quot;. .
        /// </summary>
        public static string FileDirectoryPrompt {
            get {
                return ResourceManager.GetString("FileDirectoryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved! File path:\n{filePath}.
        /// </summary>
        public static string FilePathPrompt {
            get {
                return ResourceManager.GetString("FilePathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {fileSizeInBytes:N0} bytes ({fileSizeInMB:F2} MB). .
        /// </summary>
        public static string FileSizePrompt {
            get {
                return ResourceManager.GetString("FileSizePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nGeneration and output of numbers to the console. Please wait....
        /// </summary>
        public static string GenerationAndOutputPrompt {
            get {
                return ResourceManager.GetString("GenerationAndOutputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number..
        /// </summary>
        public static string InvalidNumberPrompt {
            get {
                return ResourceManager.GetString("InvalidNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found language &quot;{lang}&quot;. Setting to EN - English...\n.
        /// </summary>
        public static string LanguageNeutralPrompt {
            get {
                return ResourceManager.GetString("LanguageNeutralPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&gt;\tEN - English\n\tES - Español\n\tUK - Українська.
        /// </summary>
        public static string LanguageOptionsPrompt {
            get {
                return ResourceManager.GetString("LanguageOptionsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your language: .
        /// </summary>
        public static string LanguagePrompt {
            get {
                return ResourceManager.GetString("LanguagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the app to language &quot;{lang}&quot;...\n.
        /// </summary>
        public static string LanguageSettingPrompt {
            get {
                return ResourceManager.GetString("LanguageSettingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the method you need:\n1. Increase (1 2 ... 9 10)\n2. Decrease (10 9 ... 2 1)\nEnter the method number: .
        /// </summary>
        public static string MethodChoicePrompt {
            get {
                return ResourceManager.GetString("MethodChoicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number (must be in the range of 1 to 2). Please try again.\nEnter number: .
        /// </summary>
        public static string MethodChoiceWrongPrompt {
            get {
                return ResourceManager.GetString("MethodChoiceWrongPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nDone! Enter the new method number and new number for the new cycle:.
        /// </summary>
        public static string NewCyclePrompt {
            get {
                return ResourceManager.GetString("NewCyclePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoPrompt {
            get {
                return ResourceManager.GetString("NoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... (Output truncated for performance).
        /// </summary>
        public static string OutputTruncatedPrompt {
            get {
                return ResourceManager.GetString("OutputTruncatedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording cancelled..
        /// </summary>
        public static string SaveFileCancelledPrompt {
            get {
                return ResourceManager.GetString("SaveFileCancelledPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save these numbers to the &quot;{fileName}&quot; file? .
        /// </summary>
        public static string SaveFileChoicePrompt {
            get {
                return ResourceManager.GetString("SaveFileChoicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File entry....
        /// </summary>
        public static string SaveFileProcessPrompt {
            get {
                return ResourceManager.GetString("SaveFileProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file?.
        /// </summary>
        public static string SaveFilePrompt {
            get {
                return ResourceManager.GetString("SaveFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {version} Android\n\n.
        /// </summary>
        public static string VersionPrompt {
            get {
                return ResourceManager.GetString("VersionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is not suitable (must be in the range of 1 to {maxNumber:N0}). Try again..
        /// </summary>
        public static string WrongNumberPrompt {
            get {
                return ResourceManager.GetString("WrongNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesPrompt {
            get {
                return ResourceManager.GetString("YesPrompt", resourceCulture);
            }
        }
    }
}
